include: package:very_good_analysis/analysis_options.yaml

analyzer:
  errors:
    invalid_annotation_target: ignore
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true
  plugins:
    - custom_lint

formatter:
  page_width: 120

linter:
  rules:
    avoid_catching_errors: false
    avoid_redundant_argument_values: false
    implementation_imports: false
    lines_longer_than_80_chars: false
    omit_local_variable_types: false
    one_member_abstracts: false
    prefer_relative_imports: false
    public_member_api_docs: false
    require_trailing_commas: false
    sort_constructors_first: false
