name: auto_route_demo
description: 'auto_route package demo'
publish_to: 'none'
version: 1.0.0

environment:
  sdk: ^3.9.0

workspace:
  - apps/desktop
  - apps/mobile
  - packages/common_router
  - packages/features/table

dev_dependencies:
  melos: ^7.0.1
  very_good_analysis: ^9.0.0

melos:
  name: auto_route_demo
  sdkPath: .fvm/flutter_sdk

  command:
    bootstrap:
      enforceLockfile: true
      runPubGetInParallel: true

      environment:
        sdk: ^3.8.1
        flutter: '>=3.27.0'

      dependencies:
        auto_route: ^10.1.2
        flutter_riverpod: ^3.0.0
        freezed_annotation: ^3.0.0
        riverpod_annotation: ^3.0.0

      dev_dependencies:
        auto_route_generator: ^10.2.4
        build_runner: ^2.5.4
        custom_lint: ^0.8.1
        freezed: ^3.2.3
        riverpod_generator: ^3.0.0
        riverpod_lint: ^3.0.0
