name: table
description: 'Table feature.'
publish_to: 'none'
resolution: workspace
version: 1.0.0

environment:
  sdk: ^3.8.1
  flutter: '>=3.27.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^3.0.0
  freezed_annotation: ^3.0.0
  riverpod_annotation: ^3.0.0

dev_dependencies:
  build_runner: ^2.5.4
  custom_lint: ^0.8.0
  freezed: ^3.0.0
  riverpod_generator: ^3.0.0
  riverpod_lint: ^3.0.0

flutter:
  uses-material-design: true
